[features]
seeds = false
skip-lint = false

[programs.devnet]
dhukuti = "egyrA1EJRsr2b7QbciVXX78U3TkPy8GQ9dTDJQHPHvo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
